# Logical Grid Puzzle. Solve the matrix
You have a 5x5 matrix filled with random  integers between 1 and 100. Write a Python function that:
1. Finds the row with maximum sum
2. Finds the column with minimum sum
3. Checks if the matrix is symetric [i.e., A[i][j] = A[j][i]].

In [2]:
import numpy as np

# Step 1. Generate a 5x5 matrix with random integers
matrix = np.random.randint(1, 101, (5, 5))

array([[73, 90, 21, 15, 82],
       [67, 38, 30, 84, 11],
       [66, 62,  3, 58, 36],
       [24, 89,  2, 50,  9],
       [15, 87, 26, 88, 38]])

In [3]:
# Step 2. Write a function to solve the tasks
def analyze_matrix(matrix):
    # Find the row with the maximus sum
    row_sums = matrix.sum(axis=1)
    max_row_index = np.argmax(row_sums)

    # Find the column with the minimun sum
    column_sums = matrix.sum(axis=0)
    min_col_index = np.argmin(column_sums)

    # Check if the matrix is symetric
    is_Symetric = np.array_equal(matrix, matrix.T)

    return max_row_index, min_col_index, is_Symetric

# Step 3. Analyze the matrix
max_row, min_col, symetric = analyze_matrix(matrix)

# print results
print('Matrix \n', matrix)
print('Row with maximus sum. ', max_row)
print('Column with minimum sum. ', min_col)
print('Is the matrix symetric? ', symetric)

Matrix 
 [[73 90 21 15 82]
 [67 38 30 84 11]
 [66 62  3 58 36]
 [24 89  2 50  9]
 [15 87 26 88 38]]
Row with maximus sum.  0
Column with minimum sum.  3
Is the matrix symetric?  False


# Mathematical Reasoning: Solve a System of Equations
Solve the following system of equations using Python:
* 3x + 4y - z = 7
* 2x - y + 3z = 3
* 5x + 2y + 2z = 8

In [4]:
import numpy as np 

# Define the coefficients matrix (A) and constants (B)
A = np.array([
    [3, 4, -1],
    [2, -1, 3],
    [5, 2, 2]
])
B = np.array([7, 3, 8])

# Solve the system of equations
solution = np.linalg.solve(A, B)

# Print the solution
print('Solution (x, y, z):', solution)

Solution (x, y, z): [0.18181818 2.         1.54545455]


# Logical Problem: Knight's Tour
Write a function to determine whether a knight on a chessboard can visit all squares of an 8x8 board exactly once (Knight's Tour). Solve the simplified version where the knight starts starts in the top-left corner, and a single path solution is sufficient.

In [1]:
def is_safe(x, y, board):
    return 0 <= x < 8 and 0 <= y < 8 and board[x][y] == -1

def knight_tour_util(x, y, move_count, board, x_moves, y_moves):
    if move_count == 64:
        return True
    
    for i in range(8):
        next_x = x + x_moves[i]
        next_y = y + y_moves[i]
        if is_safe(next_x, next_y, board):
            board[next_x][next_y] = move_count

            if knight_tour_util(next_x, next_y, move_count +1, board, x_moves, y_moves):
                return True
            
            board[next_x][next_y] = -1 # Backtracking

    return False

def knight_tour():
    board = [[-1 for _ in range(8)] for _ in range(8)]
    x_moves = [2, 1, -1, -2, -2, -1, 1, 2]
    y_moves = [1, 2, 2, 1, -1, -2, -2, -1]

    # Start from top-left corner
    board[0][0] = 0

    if knight_tour_util(0, 0, 1, board, x_moves, y_moves):
        print("Knight's tour solution")
        for row in board:
            print(row)
    
    else:
        print('No solution exists')

knight_tour()


Knight's tour solution
[0, 59, 38, 33, 30, 17, 8, 63]
[37, 34, 31, 60, 9, 62, 29, 16]
[58, 1, 36, 39, 32, 27, 18, 7]
[35, 48, 41, 26, 61, 10, 15, 28]
[42, 57, 2, 49, 40, 23, 6, 19]
[47, 50, 45, 54, 25, 20, 11, 14]
[56, 43, 52, 3, 22, 13, 24, 5]
[51, 46, 55, 44, 53, 4, 21, 12]
